### PR TITLE
Phase2 changes

### PR DESCRIPTION
**Pull request by technosaby**
- Adding the cookbook csv generated files
- Generate default "TOP" for scenarios where .seg is absent
- A script to filter tags based on JQ query

### CODE REVIEW

**Comment by brucearctor** [comment]
For some ways JQ commonly used, see:  https://about.gitlab.com/blog/2021/04/21/devops-workflows-json-format-jq-ci-cd-lint/

**Comment by brucearctor** [comment]
it strikes me as a bit strange to have python call `jq` ...  Since `jq` will need to be installed, and doesn't do much more that the native python `json` package/module.  Do consider how your script handles the case when `jq` not installed on users machines.  How does it error, prompt for installation, etc.  And, is developing that functionality worth it?  Nothing needs to change, but wanted to share some thoughts, and potential pitfalls.

**Comment by technosaby** [comment]
> it strikes me as a bit strange to have python call `jq` ... Since `jq` will need to be installed, and doesn't do much more that the native python `json` package/module. Do consider how your script handles the case when `jq` not installed on users machines. How does it error, prompt for installation, etc. And, is developing that functionality worth it? Nothing needs to change, but wanted to share some thoughts, and potential pitfalls.

@brucearctor Thanks for sharing your feedback. I am planning to install JQ in the docker container [like this](https://github.com/technosaby/gsoc2022/blob/main/Dockerfile), so there will be no scenarios when some one using my image not have JQ. Please let me know if my understanding is correct.

**Comment by brucearctor** [comment]
I could see possibilities where people would use/modify script, outside of a container.  If that's largely to be hidden from users then no reason for concern.  

Not an issue or that anything needs to change.  I'm often the person calling out problems that *might* arise in the future.

**Pull request merged**
